### ISSUE TITLE
Symfony cache has() method does not exists

### ISSUE THREAD

**Issue by kakoma** [sonata-project/SonataCacheBundle#83]
Is the symfony caching adapter mentioned in the [configuration documentation](https://sonata-project.org/bundles/cache/master/doc/reference/installation.html#configuration) complete? Unlike the other caching Adapters, the Sonata\CacheBundle\Adapter\SymfonyCache `has` method throws this exception:

`throw new UnsupportedException('Symfony cache has() method does not exists');`

Here's the method's full code:

``` php
    /**
     * {@inheritdoc}
     */
    public function has(array $keys)
    {
        throw new UnsupportedException('Symfony cache has() method does not exists');
    }
```

**Comment by core23** [comment]
Can you provide a PR to fix this @kakoma ?

**Comment by jordisala1991** [comment]
This is related: https://github.com/sonata-project/cache/issues/96

The interface forces you to have those methos, even though symfony cache dont want to implement them. One issue to talk about this should be enough. Closing this one because the other is more generic and probably it has to be fixed on cache library first.
